// ##########################################################################
// ### This file is generated by Build and Continuous Integration scripts ###
// ###   .github/workflows/buildinfo.py for local development environment ###
// ###   .github/workflows/testbuildrelease.yml for CI environment        ###
// ### Changes will be overwritten on the next build                      ###
// ##########################################################################

#include <buildinfo.hpp>

const buildEnvironment buildInfo::theBuildEnvironment{buildEnvironment::local};
const buildType buildInfo::theBuildType{buildType::development};
const int buildInfo::mainVersionDigit   = 1;
const int buildInfo::minorVersionDigit  = 0;
const int buildInfo::patchVersionDigit  = 1;
const char* buildInfo::lastCommitTag    = "23c78f8";
const char* buildInfo::buildTimeStamp   = "Sat Jan 11 13:59:59 2025";
const time_t buildInfo::buildEpoch      = 1736603999;
