// ##########################################################################
// ### This file is generated by Build and Continuous Integration scripts ###
// ###   .github/workflows/buildinfo.py for local development environment ###
// ###   .github/workflows/testbuildrelease.yml for CI environment        ###
// ### Changes will be overwritten on the next build                      ###
// ##########################################################################

#include <buildinfo.hpp>

const buildEnvironment buildInfo::theBuildEnvironment{buildEnvironment::local};
const buildType buildInfo::theBuildType{buildType::development};
const int buildInfo::mainVersionDigit   = 1;
const int buildInfo::minorVersionDigit  = 0;
const int buildInfo::patchVersionDigit  = 17;
const char* buildInfo::lastCommitTag    = "4e9cfef";
const char* buildInfo::buildTimeStamp   = "Mon Oct 07 08:35:27 2024";
const time_t buildInfo::buildEpoch      = 1728290127;
