// ##########################################################################
// ### This file is generated by Build and Continuous Integration scripts ###
// ###   .github/workflows/buildinfo.py for local development environment ###
// ###   .github/workflows/testbuildrelease.yml for CI environment        ###
// ### Changes will be overwritten on the next build                      ###
// ##########################################################################

#include <buildinfo.hpp>

const buildEnvironment buildInfo::theBuildEnvironment{buildEnvironment::local};
const buildType buildInfo::theBuildType{buildType::development};
const int buildInfo::mainVersionDigit   = 0;
const int buildInfo::minorVersionDigit  = 0;
const int buildInfo::patchVersionDigit  = 0;
const char* buildInfo::lastCommitTag    = "1d96a66";
const char* buildInfo::buildTimeStamp   = "Thu Oct 24 09:20:25 2024";
const time_t buildInfo::buildEpoch      = 1729761625;
